import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Bot, Lightbulb } from "lucide-react";
import type { TrendAnalysis } from "@shared/schema";

interface AIInsightsProps {
  analysis: TrendAnalysis;
}

export function AIInsights({ analysis }: AIInsightsProps) {
  return (
    <Card>
      <CardHeader className="pb-3 sm:pb-6">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between space-y-2 sm:space-y-0">
          <CardTitle className="text-base sm:text-lg">AI Market Insights</CardTitle>
          <div className="flex items-center space-x-2 text-xs sm:text-sm text-gray-500">
            <Bot className="w-3 h-3 sm:w-4 sm:h-4" />
            <span>Generated by AI</span>
          </div>
        </div>
      </CardHeader>
      <CardContent className="pt-0">
        <div className="grid grid-cols-1 xl:grid-cols-2 gap-4 sm:gap-6">
          <div className="p-3 sm:p-4 bg-secondary/50 rounded-lg">
            <h4 className="font-medium text-gray-900 mb-2 text-sm sm:text-base">Market Opportunity</h4>
            <p className="text-xs sm:text-sm text-gray-700 leading-relaxed">{analysis.marketOpportunity}</p>
          </div>
          
          <div className="p-3 sm:p-4 bg-blue-50 rounded-lg">
            <h4 className="font-medium text-gray-900 mb-2 text-sm sm:text-base">Recommended Strategy</h4>
            <p className="text-xs sm:text-sm text-gray-700 leading-relaxed">{analysis.recommendedStrategy}</p>
          </div>
        </div>
        
        <div className="mt-4 sm:mt-6 p-3 sm:p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
          <div className="flex items-start space-x-2 sm:space-x-3">
            <Lightbulb className="w-4 h-4 sm:w-5 sm:h-5 text-yellow-600 mt-0.5 flex-shrink-0" />
            <div className="min-w-0">
              <h4 className="font-medium text-yellow-800 text-sm sm:text-base">Key Insight</h4>
              <p className="text-xs sm:text-sm text-yellow-700 mt-1 leading-relaxed">{analysis.keyInsight}</p>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
