import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Bot, Lightbulb } from "lucide-react";
import type { TrendAnalysis } from "@shared/schema";

interface AIInsightsProps {
  analysis: TrendAnalysis;
}

export function AIInsights({ analysis }: AIInsightsProps) {
  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle>AI Market Insights</CardTitle>
          <div className="flex items-center space-x-2 text-sm text-gray-500">
            <Bot className="w-4 h-4" />
            <span>Generated by AI</span>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="p-4 bg-secondary/50 rounded-lg">
            <h4 className="font-medium text-gray-900 mb-2">Market Opportunity</h4>
            <p className="text-sm text-gray-700">{analysis.marketOpportunity}</p>
          </div>
          
          <div className="p-4 bg-blue-50 rounded-lg">
            <h4 className="font-medium text-gray-900 mb-2">Recommended Strategy</h4>
            <p className="text-sm text-gray-700">{analysis.recommendedStrategy}</p>
          </div>
        </div>
        
        <div className="mt-6 p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
          <div className="flex items-start space-x-3">
            <Lightbulb className="w-5 h-5 text-yellow-600 mt-0.5 flex-shrink-0" />
            <div>
              <h4 className="font-medium text-yellow-800">Key Insight</h4>
              <p className="text-sm text-yellow-700 mt-1">{analysis.keyInsight}</p>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
